// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"userId"`
	SkillID        uuid.UUID      `json:"skillId"`
	Skill          *Skill         `json:"skill"`
	Name           string         `json:"name"`
	Duration       int            `json:"duration"`
	Date           time.Time      `json:"date"`
	Notes          *string        `json:"notes,omitempty"`
	Status         ActivityStatus `json:"status"`
	StartedAt      *time.Time     `json:"startedAt,omitempty"`
	PausedAt       *time.Time     `json:"pausedAt,omitempty"`
	PausedDuration *int           `json:"pausedDuration,omitempty"`
	CreatedAt      time.Time      `json:"createdAt"`
}

type ActivityConnection struct {
	Nodes      []*Activity `json:"nodes"`
	TotalCount int         `json:"totalCount"`
	HasMore    bool        `json:"hasMore"`
}

type ActivityFilter struct {
	SkillID   *uuid.UUID      `json:"skillId,omitempty"`
	StartDate *time.Time      `json:"startDate,omitempty"`
	EndDate   *time.Time      `json:"endDate,omitempty"`
	Status    *ActivityStatus `json:"status,omitempty"`
}

type ActivityStats struct {
	TotalActivities int           `json:"totalActivities"`
	TotalMinutes    int           `json:"totalMinutes"`
	TotalHours      float64       `json:"totalHours"`
	SkillBreakdown  []*SkillStats `json:"skillBreakdown"`
	Period          string        `json:"period"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateActivityInput struct {
	SkillID  uuid.UUID      `json:"skillId"`
	Name     string         `json:"name"`
	Duration int            `json:"duration"`
	Date     time.Time      `json:"date"`
	Notes    *string        `json:"notes,omitempty"`
	Status   ActivityStatus `json:"status"`
}

type CreateEventInput struct {
	Title          string                   `json:"title"`
	Description    *string                  `json:"description,omitempty"`
	Type           EventType                `json:"type"`
	StartTime      time.Time                `json:"startTime"`
	EndTime        time.Time                `json:"endTime"`
	AllDay         *bool                    `json:"allDay,omitempty"`
	Recurrence     *Recurrence              `json:"recurrence,omitempty"`
	RecurrenceRule *string                  `json:"recurrenceRule,omitempty"`
	RecurrenceEnd  *time.Time               `json:"recurrenceEnd,omitempty"`
	SkillID        *uuid.UUID               `json:"skillId,omitempty"`
	ActivityID     *uuid.UUID               `json:"activityId,omitempty"`
	LearningPlanID *uuid.UUID               `json:"learningPlanId,omitempty"`
	Notifications  *EventNotificationsInput `json:"notifications,omitempty"`
	Color          *string                  `json:"color,omitempty"`
	Location       *string                  `json:"location,omitempty"`
	Attendees      []string                 `json:"attendees,omitempty"`
	Tags           []string                 `json:"tags,omitempty"`
}

type CreateFileInput struct {
	Filename             string   `json:"filename"`
	Directory            string   `json:"directory"`
	OriginalFilename     string   `json:"originalFilename"`
	MimeType             string   `json:"mimeType"`
	FileSize             int      `json:"fileSize"`
	TelegramFileID       *string  `json:"telegramFileId,omitempty"`
	TelegramFileUniqueID *string  `json:"telegramFileUniqueId,omitempty"`
	TelegramMessageID    *int     `json:"telegramMessageId,omitempty"`
	StoragePath          string   `json:"storagePath"`
	Tags                 []string `json:"tags,omitempty"`
	Description          *string  `json:"description,omitempty"`
}

type CreateLearningPlanEdgeInput struct {
	LearningPlanID uuid.UUID `json:"learningPlanId"`
	SourceNodeID   uuid.UUID `json:"sourceNodeId"`
	TargetNodeID   uuid.UUID `json:"targetNodeId"`
}

type CreateLearningPlanInput struct {
	Name               string         `json:"name"`
	Description        *string        `json:"description,omitempty"`
	SkillIds           []uuid.UUID    `json:"skillIds"`
	Schedule           *ScheduleInput `json:"schedule"`
	TargetHoursPerWeek *float64       `json:"targetHoursPerWeek,omitempty"`
	StartDate          time.Time      `json:"startDate"`
	EndDate            *time.Time     `json:"endDate,omitempty"`
}

type CreateLearningPlanNodeInput struct {
	LearningPlanID uuid.UUID  `json:"learningPlanId"`
	SkillID        *uuid.UUID `json:"skillId,omitempty"`
	Title          string     `json:"title"`
	Description    *string    `json:"description,omitempty"`
	PlannedHours   float64    `json:"plannedHours"`
	PositionX      float64    `json:"positionX"`
	PositionY      float64    `json:"positionY"`
}

type CreateNoteInput struct {
	Title      string     `json:"title"`
	Content    string     `json:"content"`
	Tags       []string   `json:"tags,omitempty"`
	LinkedType *string    `json:"linkedType,omitempty"`
	LinkedID   *uuid.UUID `json:"linkedId,omitempty"`
}

type CreateReminderInput struct {
	Title                string            `json:"title"`
	Description          *string           `json:"description,omitempty"`
	DueTime              time.Time         `json:"dueTime"`
	Priority             *ReminderPriority `json:"priority,omitempty"`
	RepeatPattern        *RepeatPattern    `json:"repeatPattern,omitempty"`
	RepeatRule           *string           `json:"repeatRule,omitempty"`
	RepeatEnd            *time.Time        `json:"repeatEnd,omitempty"`
	EventID              *uuid.UUID        `json:"eventId,omitempty"`
	NotificationChannels []string          `json:"notificationChannels,omitempty"`
	ReminderTimes        []int             `json:"reminderTimes,omitempty"`
	Tags                 []string          `json:"tags,omitempty"`
}

type CreateSkillInput struct {
	Name  string  `json:"name"`
	Level *string `json:"level,omitempty"`
	Notes *string `json:"notes,omitempty"`
}

type Directory struct {
	Path           string   `json:"path"`
	Parent         *string  `json:"parent,omitempty"`
	Subdirectories []string `json:"subdirectories"`
	FileCount      int      `json:"fileCount"`
}

type Event struct {
	ID             uuid.UUID           `json:"id"`
	UserID         uuid.UUID           `json:"userId"`
	Title          string              `json:"title"`
	Description    *string             `json:"description,omitempty"`
	Type           EventType           `json:"type"`
	StartTime      time.Time           `json:"startTime"`
	EndTime        time.Time           `json:"endTime"`
	AllDay         bool                `json:"allDay"`
	Recurrence     Recurrence          `json:"recurrence"`
	RecurrenceRule *string             `json:"recurrenceRule,omitempty"`
	RecurrenceEnd  *time.Time          `json:"recurrenceEnd,omitempty"`
	SkillID        *uuid.UUID          `json:"skillId,omitempty"`
	Skill          *Skill              `json:"skill,omitempty"`
	ActivityID     *uuid.UUID          `json:"activityId,omitempty"`
	Activity       *Activity           `json:"activity,omitempty"`
	LearningPlanID *uuid.UUID          `json:"learningPlanId,omitempty"`
	LearningPlan   *LearningPlan       `json:"learningPlan,omitempty"`
	Notifications  *EventNotifications `json:"notifications,omitempty"`
	Color          *string             `json:"color,omitempty"`
	Location       *string             `json:"location,omitempty"`
	Attendees      []string            `json:"attendees,omitempty"`
	Tags           []string            `json:"tags,omitempty"`
	CreatedAt      time.Time           `json:"createdAt"`
	UpdatedAt      time.Time           `json:"updatedAt"`
}

type EventNotification struct {
	Event         *Event `json:"event"`
	Message       string `json:"message"`
	MinutesBefore int    `json:"minutesBefore"`
}

type EventNotifications struct {
	Enabled         bool     `json:"enabled"`
	Channels        []string `json:"channels"`
	ReminderMinutes []int    `json:"reminderMinutes"`
}

type EventNotificationsInput struct {
	Enabled         bool     `json:"enabled"`
	Channels        []string `json:"channels"`
	ReminderMinutes []int    `json:"reminderMinutes"`
}

type File struct {
	ID                   uuid.UUID `json:"id"`
	UserID               uuid.UUID `json:"userId"`
	Filename             string    `json:"filename"`
	Directory            string    `json:"directory"`
	OriginalFilename     string    `json:"originalFilename"`
	MimeType             string    `json:"mimeType"`
	FileSize             int       `json:"fileSize"`
	TelegramFileID       *string   `json:"telegramFileId,omitempty"`
	TelegramFileUniqueID *string   `json:"telegramFileUniqueId,omitempty"`
	TelegramMessageID    *int      `json:"telegramMessageId,omitempty"`
	StoragePath          string    `json:"storagePath"`
	Tags                 []string  `json:"tags"`
	Description          *string   `json:"description,omitempty"`
	CreatedAt            time.Time `json:"createdAt"`
	UpdatedAt            time.Time `json:"updatedAt"`
}

type FileConnection struct {
	Nodes      []*File `json:"nodes"`
	TotalCount int     `json:"totalCount"`
	HasMore    bool    `json:"hasMore"`
}

type FileFilter struct {
	Directory   *string    `json:"directory,omitempty"`
	MimeType    *string    `json:"mimeType,omitempty"`
	Tags        []string   `json:"tags,omitempty"`
	SearchQuery *string    `json:"searchQuery,omitempty"`
	StartDate   *time.Time `json:"startDate,omitempty"`
	EndDate     *time.Time `json:"endDate,omitempty"`
}

type LearningPlan struct {
	ID                 uuid.UUID           `json:"id"`
	UserID             uuid.UUID           `json:"userId"`
	Name               string              `json:"name"`
	Description        *string             `json:"description,omitempty"`
	SkillIds           []uuid.UUID         `json:"skillIds"`
	Skills             []*Skill            `json:"skills"`
	Schedule           *Schedule           `json:"schedule"`
	TargetHoursPerWeek *float64            `json:"targetHoursPerWeek,omitempty"`
	StartDate          time.Time           `json:"startDate"`
	EndDate            *time.Time          `json:"endDate,omitempty"`
	CompletedHours     float64             `json:"completedHours"`
	Nodes              []*LearningPlanNode `json:"nodes"`
	Edges              []*LearningPlanEdge `json:"edges"`
	CreatedAt          time.Time           `json:"createdAt"`
	UpdatedAt          time.Time           `json:"updatedAt"`
}

type LearningPlanEdge struct {
	ID             uuid.UUID `json:"id"`
	LearningPlanID uuid.UUID `json:"learningPlanId"`
	SourceNodeID   uuid.UUID `json:"sourceNodeId"`
	TargetNodeID   uuid.UUID `json:"targetNodeId"`
	CreatedAt      time.Time `json:"createdAt"`
}

type LearningPlanNode struct {
	ID             uuid.UUID  `json:"id"`
	LearningPlanID uuid.UUID  `json:"learningPlanId"`
	SkillID        *uuid.UUID `json:"skillId,omitempty"`
	Skill          *Skill     `json:"skill,omitempty"`
	Title          string     `json:"title"`
	Description    *string    `json:"description,omitempty"`
	PlannedHours   float64    `json:"plannedHours"`
	CompletedHours float64    `json:"completedHours"`
	PositionX      float64    `json:"positionX"`
	PositionY      float64    `json:"positionY"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
}

type Mutation struct {
}

type Note struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"userId"`
	Title      string     `json:"title"`
	Content    string     `json:"content"`
	Tags       []string   `json:"tags"`
	LinkedType *string    `json:"linkedType,omitempty"`
	LinkedID   *uuid.UUID `json:"linkedId,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}

type NoteConnection struct {
	Nodes      []*Note `json:"nodes"`
	TotalCount int     `json:"totalCount"`
	HasMore    bool    `json:"hasMore"`
}

type NoteFilter struct {
	Tags       []string   `json:"tags,omitempty"`
	LinkedType *string    `json:"linkedType,omitempty"`
	LinkedID   *uuid.UUID `json:"linkedId,omitempty"`
}

type Notification struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"userId"`
	EventID          *uuid.UUID `json:"eventId,omitempty"`
	Event            *Event     `json:"event,omitempty"`
	ReminderID       *uuid.UUID `json:"reminderId,omitempty"`
	Reminder         *Reminder  `json:"reminder,omitempty"`
	ScheduledTime    time.Time  `json:"scheduledTime"`
	Sent             bool       `json:"sent"`
	SentAt           *time.Time `json:"sentAt,omitempty"`
	Channel          string     `json:"channel"`
	NotificationType string     `json:"notificationType"`
	Message          *string    `json:"message,omitempty"`
	CreatedAt        time.Time  `json:"createdAt"`
}

type NotificationConnection struct {
	Nodes      []*Notification `json:"nodes"`
	TotalCount int             `json:"totalCount"`
	HasMore    bool            `json:"hasMore"`
}

type Query struct {
}

type Reminder struct {
	ID                   uuid.UUID        `json:"id"`
	UserID               uuid.UUID        `json:"userId"`
	Title                string           `json:"title"`
	Description          *string          `json:"description,omitempty"`
	DueTime              time.Time        `json:"dueTime"`
	Completed            bool             `json:"completed"`
	CompletedAt          *time.Time       `json:"completedAt,omitempty"`
	Priority             ReminderPriority `json:"priority"`
	RepeatPattern        RepeatPattern    `json:"repeatPattern"`
	RepeatRule           *string          `json:"repeatRule,omitempty"`
	RepeatEnd            *time.Time       `json:"repeatEnd,omitempty"`
	EventID              *uuid.UUID       `json:"eventId,omitempty"`
	Event                *Event           `json:"event,omitempty"`
	NotificationChannels []string         `json:"notificationChannels"`
	ReminderTimes        []int            `json:"reminderTimes"`
	Tags                 []string         `json:"tags"`
	CreatedAt            time.Time        `json:"createdAt"`
	UpdatedAt            time.Time        `json:"updatedAt"`
}

type ReminderConnection struct {
	Nodes      []*Reminder `json:"nodes"`
	TotalCount int         `json:"totalCount"`
	HasMore    bool        `json:"hasMore"`
}

type ReminderFilter struct {
	Completed *bool             `json:"completed,omitempty"`
	Priority  *ReminderPriority `json:"priority,omitempty"`
	Tags      []string          `json:"tags,omitempty"`
	EventID   *uuid.UUID        `json:"eventId,omitempty"`
	StartDate *time.Time        `json:"startDate,omitempty"`
	EndDate   *time.Time        `json:"endDate,omitempty"`
}

type ReminderNotification struct {
	Reminder *Reminder `json:"reminder"`
	Message  string    `json:"message"`
}

type Schedule struct {
	Frequency       string   `json:"frequency"`
	DurationMinutes int      `json:"durationMinutes"`
	PreferredTimes  []string `json:"preferredTimes"`
	PreferredDays   []int    `json:"preferredDays"`
	AutoSchedule    bool     `json:"autoSchedule"`
}

type ScheduleInput struct {
	Frequency       string   `json:"frequency"`
	DurationMinutes int      `json:"durationMinutes"`
	PreferredTimes  []string `json:"preferredTimes"`
	PreferredDays   []int    `json:"preferredDays"`
	AutoSchedule    bool     `json:"autoSchedule"`
}

type Skill struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	Name      string    `json:"name"`
	Level     *string   `json:"level,omitempty"`
	Notes     *string   `json:"notes,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type SkillStats struct {
	SkillID       uuid.UUID `json:"skillId"`
	SkillName     string    `json:"skillName"`
	ActivityCount int       `json:"activityCount"`
	TotalMinutes  int       `json:"totalMinutes"`
	TotalHours    float64   `json:"totalHours"`
}

type Subscription struct {
}

type UpdateActivityInput struct {
	Name     *string         `json:"name,omitempty"`
	Duration *int            `json:"duration,omitempty"`
	Date     *time.Time      `json:"date,omitempty"`
	Notes    *string         `json:"notes,omitempty"`
	Status   *ActivityStatus `json:"status,omitempty"`
}

type UpdateEventInput struct {
	Title          *string                  `json:"title,omitempty"`
	Description    *string                  `json:"description,omitempty"`
	Type           *EventType               `json:"type,omitempty"`
	StartTime      *time.Time               `json:"startTime,omitempty"`
	EndTime        *time.Time               `json:"endTime,omitempty"`
	AllDay         *bool                    `json:"allDay,omitempty"`
	Recurrence     *Recurrence              `json:"recurrence,omitempty"`
	RecurrenceRule *string                  `json:"recurrenceRule,omitempty"`
	RecurrenceEnd  *time.Time               `json:"recurrenceEnd,omitempty"`
	SkillID        *uuid.UUID               `json:"skillId,omitempty"`
	ActivityID     *uuid.UUID               `json:"activityId,omitempty"`
	LearningPlanID *uuid.UUID               `json:"learningPlanId,omitempty"`
	Notifications  *EventNotificationsInput `json:"notifications,omitempty"`
	Color          *string                  `json:"color,omitempty"`
	Location       *string                  `json:"location,omitempty"`
	Attendees      []string                 `json:"attendees,omitempty"`
	Tags           []string                 `json:"tags,omitempty"`
}

type UpdateFileInput struct {
	Filename       *string  `json:"filename,omitempty"`
	Directory      *string  `json:"directory,omitempty"`
	Tags           []string `json:"tags,omitempty"`
	Description    *string  `json:"description,omitempty"`
	TelegramFileID *string  `json:"telegramFileId,omitempty"`
}

type UpdateLearningPlanInput struct {
	Name               *string        `json:"name,omitempty"`
	Description        *string        `json:"description,omitempty"`
	SkillIds           []uuid.UUID    `json:"skillIds,omitempty"`
	Schedule           *ScheduleInput `json:"schedule,omitempty"`
	TargetHoursPerWeek *float64       `json:"targetHoursPerWeek,omitempty"`
	StartDate          *time.Time     `json:"startDate,omitempty"`
	EndDate            *time.Time     `json:"endDate,omitempty"`
}

type UpdateLearningPlanNodeInput struct {
	SkillID        *uuid.UUID `json:"skillId,omitempty"`
	Title          *string    `json:"title,omitempty"`
	Description    *string    `json:"description,omitempty"`
	PlannedHours   *float64   `json:"plannedHours,omitempty"`
	CompletedHours *float64   `json:"completedHours,omitempty"`
	PositionX      *float64   `json:"positionX,omitempty"`
	PositionY      *float64   `json:"positionY,omitempty"`
}

type UpdateNoteInput struct {
	Title      *string    `json:"title,omitempty"`
	Content    *string    `json:"content,omitempty"`
	Tags       []string   `json:"tags,omitempty"`
	LinkedType *string    `json:"linkedType,omitempty"`
	LinkedID   *uuid.UUID `json:"linkedId,omitempty"`
}

type UpdateReminderInput struct {
	Title                *string           `json:"title,omitempty"`
	Description          *string           `json:"description,omitempty"`
	DueTime              *time.Time        `json:"dueTime,omitempty"`
	Completed            *bool             `json:"completed,omitempty"`
	Priority             *ReminderPriority `json:"priority,omitempty"`
	RepeatPattern        *RepeatPattern    `json:"repeatPattern,omitempty"`
	RepeatRule           *string           `json:"repeatRule,omitempty"`
	RepeatEnd            *time.Time        `json:"repeatEnd,omitempty"`
	EventID              *uuid.UUID        `json:"eventId,omitempty"`
	NotificationChannels []string          `json:"notificationChannels,omitempty"`
	ReminderTimes        []int             `json:"reminderTimes,omitempty"`
	Tags                 []string          `json:"tags,omitempty"`
}

type UpdateSkillInput struct {
	Name  *string `json:"name,omitempty"`
	Level *string `json:"level,omitempty"`
	Notes *string `json:"notes,omitempty"`
}

type User struct {
	ID         uuid.UUID `json:"id"`
	Email      string    `json:"email"`
	Name       string    `json:"name"`
	TelegramID *int      `json:"telegramId,omitempty"`
	IsService  bool      `json:"isService"`
	IsActive   bool      `json:"isActive"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type ActivityStatus string

const (
	ActivityStatusCompleted ActivityStatus = "COMPLETED"
	ActivityStatusActive    ActivityStatus = "ACTIVE"
	ActivityStatusPaused    ActivityStatus = "PAUSED"
)

var AllActivityStatus = []ActivityStatus{
	ActivityStatusCompleted,
	ActivityStatusActive,
	ActivityStatusPaused,
}

func (e ActivityStatus) IsValid() bool {
	switch e {
	case ActivityStatusCompleted, ActivityStatusActive, ActivityStatusPaused:
		return true
	}
	return false
}

func (e ActivityStatus) String() string {
	return string(e)
}

func (e *ActivityStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityStatus", str)
	}
	return nil
}

func (e ActivityStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EventType string

const (
	EventTypeActivity EventType = "ACTIVITY"
	EventTypeLearning EventType = "LEARNING"
	EventTypeMeeting  EventType = "MEETING"
	EventTypeReminder EventType = "REMINDER"
	EventTypeCustom   EventType = "CUSTOM"
)

var AllEventType = []EventType{
	EventTypeActivity,
	EventTypeLearning,
	EventTypeMeeting,
	EventTypeReminder,
	EventTypeCustom,
}

func (e EventType) IsValid() bool {
	switch e {
	case EventTypeActivity, EventTypeLearning, EventTypeMeeting, EventTypeReminder, EventTypeCustom:
		return true
	}
	return false
}

func (e EventType) String() string {
	return string(e)
}

func (e *EventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventType", str)
	}
	return nil
}

func (e EventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Recurrence string

const (
	RecurrenceNone    Recurrence = "NONE"
	RecurrenceDaily   Recurrence = "DAILY"
	RecurrenceWeekly  Recurrence = "WEEKLY"
	RecurrenceMonthly Recurrence = "MONTHLY"
	RecurrenceCustom  Recurrence = "CUSTOM"
)

var AllRecurrence = []Recurrence{
	RecurrenceNone,
	RecurrenceDaily,
	RecurrenceWeekly,
	RecurrenceMonthly,
	RecurrenceCustom,
}

func (e Recurrence) IsValid() bool {
	switch e {
	case RecurrenceNone, RecurrenceDaily, RecurrenceWeekly, RecurrenceMonthly, RecurrenceCustom:
		return true
	}
	return false
}

func (e Recurrence) String() string {
	return string(e)
}

func (e *Recurrence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Recurrence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Recurrence", str)
	}
	return nil
}

func (e Recurrence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Recurrence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Recurrence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReminderPriority string

const (
	ReminderPriorityLow    ReminderPriority = "LOW"
	ReminderPriorityMedium ReminderPriority = "MEDIUM"
	ReminderPriorityHigh   ReminderPriority = "HIGH"
)

var AllReminderPriority = []ReminderPriority{
	ReminderPriorityLow,
	ReminderPriorityMedium,
	ReminderPriorityHigh,
}

func (e ReminderPriority) IsValid() bool {
	switch e {
	case ReminderPriorityLow, ReminderPriorityMedium, ReminderPriorityHigh:
		return true
	}
	return false
}

func (e ReminderPriority) String() string {
	return string(e)
}

func (e *ReminderPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReminderPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReminderPriority", str)
	}
	return nil
}

func (e ReminderPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReminderPriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReminderPriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepeatPattern string

const (
	RepeatPatternNone    RepeatPattern = "NONE"
	RepeatPatternDaily   RepeatPattern = "DAILY"
	RepeatPatternWeekly  RepeatPattern = "WEEKLY"
	RepeatPatternMonthly RepeatPattern = "MONTHLY"
	RepeatPatternYearly  RepeatPattern = "YEARLY"
	RepeatPatternCustom  RepeatPattern = "CUSTOM"
)

var AllRepeatPattern = []RepeatPattern{
	RepeatPatternNone,
	RepeatPatternDaily,
	RepeatPatternWeekly,
	RepeatPatternMonthly,
	RepeatPatternYearly,
	RepeatPatternCustom,
}

func (e RepeatPattern) IsValid() bool {
	switch e {
	case RepeatPatternNone, RepeatPatternDaily, RepeatPatternWeekly, RepeatPatternMonthly, RepeatPatternYearly, RepeatPatternCustom:
		return true
	}
	return false
}

func (e RepeatPattern) String() string {
	return string(e)
}

func (e *RepeatPattern) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepeatPattern(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepeatPattern", str)
	}
	return nil
}

func (e RepeatPattern) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepeatPattern) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepeatPattern) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
