'use client'

import { getClient } from './helpers/api-client'

/**
 * User Account Management API
 */

export interface User {
  id: string;
  email: string;
  name: string;
  telegramId?: number;
  isService: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// GraphQL Mutations
const LINK_TELEGRAM_MUTATION = `
  mutation LinkTelegram($telegramId: Int!, $telegramUsername: String) {
    linkTelegram(telegramId: $telegramId, telegramUsername: $telegramUsername) {
      id
      email
      name
      telegramId
      isService
      isActive
      createdAt
      updatedAt
    }
  }
`

/**
 * Link Telegram account to authenticated user
 * @param telegramId - Telegram user ID
 * @param telegramUsername - Optional Telegram username
 */
export async function linkTelegram(telegramId: number, telegramUsername?: string): Promise<User> {
  const client = getClient()
  const result = await client.mutation(LINK_TELEGRAM_MUTATION, { 
    telegramId, 
    telegramUsername 
  }).toPromise()
  
  if (result.error) {
    console.error('Error linking Telegram:', result.error)
    throw new Error(result.error.message)
  }
  
  return result.data.linkTelegram
}

/**
 * Generate a unique linking code for Telegram bot registration
 * This can be used to securely link a Telegram account
 */
export function generateTelegramLinkingCode(userId: string): string {
  // Simple implementation - in production, this should be a secure token
  // generated by the backend and stored temporarily
  return `LINK_${userId.substring(0, 8).toUpperCase()}`
}
